### ISSUE TITLE
1. An introduction to binary response variables

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/logistic-regression-public-health#1]
-----------------------------------------------
1. An introduction to binary response variables
https://carpentries-incubator.github.io/logistic-regression-public-health/01-introBinary/index.html

Note: to include what binary response variables are and the meaning of success and failure in the statistical thinking workshop

That is, variables which can take on two values.
->
That is, variables which can take one of two possible values.

vs.
->
or

For example, we may be interested in the probability that individuals between the ages of 55 and 66, who have once been smokers, are still smoking during the NHANES study.
->
For example, if we consider individuals between the ages of 55 and 66, we may be interested in the probability that individuals who once smoked, are still smoking during the NHANES study.

Add that we define success as still smoking and failure as no longer smoking.

In the we calculate section, it may be clearer if we say something like: We calculate these values with four operations:
1. removing the empty rows with drop_na
2. ....etc

When I follow set up
https://carpentries-incubator.github.io/simple-linear-regression-public-health/setup.html

-----------------------------------------------
2. An introduction to logistic regression
https://carpentries-incubator.github.io/logistic-regression-public-health/02-introLogistic/index.html

dat %>%
  drop_na(SmokeNow) %>%
  filter(between(Age, 55, 66)) %>%
  count(SmokeNow, name = "n") %>%
  mutate(prop = n/sum(n))

produces:

Race1    SmokeNow     n  prop
   <fct>    <fct>    <int> <dbl>
 1 Black    No          48 0.585
 2 Black    Yes         34 0.415
 3 Hispanic No          16 0.727
 4 Hispanic Yes          6 0.273
 5 Mexican  No          23 0.575
 6 Mexican  Yes         17 0.425
 7 White    No         252 0.632
 8 White    Yes        147 0.368
 9 Other    No          20 0.606
10 Other    Yes         13 0.394

We need to use ungroup() at the end of piped operations in set up

This is true as a general rule
->
This is true because there are only two possible outcomes.

Following https://carpentries-incubator.github.io/simple-linear-regression-public-health/setup.html means there is no FEV1. I'm a bit confused as FEV1 doesn't seem to exist in NHANES or NHANESraw

I have paused at this point.

**Comment by ezherman** [comment]
Hi @3mmaRand, with the setup page updated, I do not seem to need `ungroup()`. The result from

`dat %>%
drop_na(SmokeNow) %>%
filter(between(Age, 55, 66)) %>%
count(SmokeNow, name = "n") %>%
mutate(prop = n/sum(n))`

is 

  SmokeNow   n      prop
1       No 359 0.6232639
2      Yes 217 0.3767361

Could you check whether your RStudio still requires `ungroup()`?

**Comment by 3mmaRand** [comment]
@ezherman yes I do.
I'm using:
R version 4.0.4 (2021-02-15)

 [1] Hmisc_4.5-0     Formula_1.2-4   survival_3.2-10 lattice_0.20-41
 [5] tidyr_1.1.3     dplyr_1.0.5     jtools_2.1.3    cowplot_1.1.1  
 [9] ggplot2_3.3.3   NHANES_2.1.0   

Happy to update if that's the issue. I guess it will be a dplyr thing. But I think it would be better to use ungroup() because the data retains metadata about the grouping without it cos that's what group_by() returns https://dplyr.tidyverse.org/reference/group_by.html
